### ISSUE TITLE
Font size can not be controlled.

### ISSUE THREAD

**Issue by xncbf** [wooseopkim/hangul-online#1]
![image](https://cloud.githubusercontent.com/assets/9462045/22775301/5f3fccf6-eeee-11e6-855b-bb3126cc39f0.png)
스크롤을 움직이면 폰트 사이즈가 바뀌도록 의도하신건가요?
맞다면 아직 구현이 안된건가요?

**Comment by wooseopkim** [comment]
음... *제 기계에서는 되는데...* 사용하시는 브라우저 버전 알 수 있을까요?

**Comment by xncbf** [comment]
크롬 버전 56.0.2924.87 (64-bit)
입니다

**Comment by wooseopkim** [comment]
아.. 일단은 제 기계에서도 파이어폭스에선 안 되네요 확인해보겠습니다!

**Comment by wooseopkim** [comment]
제 컴퓨터에서도 안 되네요 코드를 제가 잘못 건드린 것 같습니다 분명 됐었는데... 빨리 고쳐야겠네요

**Comment by wooseopkim** [comment]
수정해서 지금 파이어베이스에 배포 걸어놨구요, 확인되는 대로 이슈 닫겠습니다. 감사합니다.
