### ISSUE TITLE
크로스 브라우징 문제

### ISSUE THREAD

**Issue by xncbf** [wooseopkim/hangul-online#3]
익스플로러에서는 아예 틀이 깨져서 나오고 크롬을 제외한 브라우저에서는 스크롤바에 원이 위로 떠있습니다

**Comment by wooseopkim** [comment]
IE 버전이 어떻게 되시나요? 그리고 원 문제는 고치려고 했었는데 깜빡했었네요... 시간이 나는대로 수정하겠습니다.

**Comment by wooseopkim** [comment]
1. 제 기기에서 IE/엣지가 모두 먹통이라 지금 작업이 불가하기도 하지만,
2. IE/엣지는 웹폰트 지원이 워낙 미비하여 지원 대상이 아니므로 생략합니다.

파이어폭스 기준으로 레인지 인풋 CSS 수정했습니다. 감사합니다.
