### ISSUE TITLE
좋은 사이트 만들어주셔서 감사합니다. 

### ISSUE THREAD

**Issue by easylogic** [wooseopkim/hangul-online#7]
최근에 폰트에 관심이 많아서 찾아보다 괜찮은 사이트를 발견했네요. 

많은 사람들에게 도움이 될 것 같습니다. 
감사합니다.

**Comment by wooseopkim** [comment]
감사합니다 ㅋㅋㅋ 기술적 난점도 있고 실력 부족도 있어서 아직 부족한 부분이 많은데, 여유도 잘 안 나고 해서 계속 방치하고 있네요... 간간히라도 유용하게 쓰실 수 있다면 좋겠습니다
